
export const eldoretLocations = [
  'Action',
  'Annex (Annexe)',
  'Bungoma Road',
  'CBD',
  'Chepkanga',
  'Chepkoilel',
  'Chepkoilel Junction',
  'Cheptiret',
  'Elgon View',
  'Huruma',
  'Jerusalem',
  'Kahang',
  'Kamukunji',
  'Kapseret',
  'Kapsoya',
  'Kimumu',
  'Kipkaren',
  'Kipkorgot',
  'Kokwas',
  'Kossin',
  'Kuinet',
  'Langas',
  'Maili Nne',
  'Marura',
  'Milimani',
  'Munyaka',
  'Mwanzo',
  'Pioneer',
  'Sergoit',
  'Shiori',
  'Stadium/Industrial wards',
  'Upper Elgon View / Racecourse',
  'West Indies'
];
