
export const eldoretLocations = [
  'Elgon View',
  'Upper Elgon View / Racecourse',
  'Pioneer',
  'Kapsoya',
  'West Indies',
  'Mwanzo',
  'Action',
  'Annex (Annexe)',
  'Huruma',
  'Munyaka',
  'Langas',
  'Maili Nne',
  'Kamukunji',
  'Kimumu',
  'Jerusalem',
  'Chepkoilel',
  'Kipkaren',
  'Milimani',
  'Shiori',
  'Bungoma Road',
  'Kapseret',
  'Kuinet',
  'Kipkorgot',
  'Sergoit',
  'Cheptiret',
  'Kahang',
  'CBD',
  'Stadium/Industrial wards'
];
