// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htbnolnksxidbnobdgjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0Ym5vbG5rc3hpZGJub2JkZ2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjc2NjEsImV4cCI6MjA2NTg0MzY2MX0.QSlJ5m81FI2fGyXuKgocNq8yKlFIWJ6SuLhuySH5EB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);